services:
  - type: web
    name: personal-guestbook-api
    env: python
    rootDir: personal-profile/backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /api/health
